name: display all logging methods

on: workflow_dispatch

jobs:
  logging:
    name: logging
    runs-on: ubuntu-latest
    steps:
      - name: å±•ç¤º echo èªæ³•
        run: |
          echo "This is a standard output message"
          echo "This is a standard error message" >&2
          echo "::warning::This is a warning message"
          echo "::error::This is an error message"
          echo "::debug::This is a debug message"
          echo "::notice::This is a notice message"

      - name: å±•ç¤º echo åˆ†çµ„æ•ˆæœ
        run: |
          echo "::group::ğŸ“¦ ç¬¬ä¸€å€‹åˆ†çµ„"
          echo "é€™è£¡æ˜¯åˆ†çµ„å…§å®¹ 1"
          echo "é€™è£¡æ˜¯åˆ†çµ„å…§å®¹ 2"
          echo "é€™è£¡æ˜¯åˆ†çµ„å…§å®¹ 3"
          echo "::endgroup::"

          echo "::group::ğŸ§ª ç¬¬äºŒå€‹åˆ†çµ„"
          echo "é€™æ˜¯å¦ä¸€å€‹åˆ†çµ„"
          echo "å¯ä»¥çœ‹åˆ°å…§å®¹è¢«æ‘ºç–Šèµ·ä¾†"
          echo "::endgroup::"

          echo "::group::ğŸ—ï¸ ç¬¬ä¸‰å€‹åˆ†çµ„"
          echo "åˆ†çµ„å¯ä»¥è®“é•·è¼¸å‡ºæ›´æ•´æ½”"
          echo "é»æ“Šå¯ä»¥å±•é–‹/æ”¶åˆ"
          echo "::endgroup::"

      - name: å±•ç¤º core èªæ³•
        uses: actions/github-script@v7
        with:
          script: |
            core.info("This is a core.info message");
            core.warning("This is a warning");
            core.error("This is an error");
            core.notice("Notice è¨Šæ¯");

      - name: å±•ç¤º core åˆ†çµ„æ•ˆæœ
        uses: actions/github-script@v7
        with:
          script: |
            core.startGroup("ç¬¬ä¸€å€‹åˆ†çµ„");
            console.log('a')
            console.log('b')
            console.log('c')
            core.endGroup();

            core.startGroup("ç¬¬äºŒå€‹åˆ†çµ„");
            core.error('é€™æ˜¯éŒ¯èª¤è¨Šæ¯')
            core.endGroup();

            core.startGroup("ç¬¬ä¸‰å€‹åˆ†çµ„");
            console.log('d')
            core.endGroup();

      - name: å±•ç¤º console èªæ³•
        uses: actions/github-script@v7
        with:
          script: |
            console.log("This is a console log message")
            console.warn("This is a console warning message")
            console.error("This is a console error message")
